services:
  - type: web
    name: personal-book-manager
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FLASK_ENV
        value: production
